#!/bin/bash
# Display MOTD banner

echo ""
echo "  ___ _   _ _    _    ___ _____ _   ___ _  __"
echo " | __| | | | |  | |  / __|_   _/_\ / __| |/ /"
echo " | _|| |_| | |__| |__\__ \ | |/ _ \ (__| ' < "
echo " |_|  \___/|____|____|___/ |_/_/ \_\___|_|\_\\"
echo ""
echo "  _      _   _  _  ___ _   _   _   ___ ___   __  __  ___  ___  ___ _    ___ "
echo " | |    /_\ | \| |/ __| | | | /_\ / __| __| |  \/  |/ _ \|   \| __| |  / __|"
echo " | |__ / _ \| .\` | (_ | |_| |/ _ \ (_ | _|  | |\/| | (_) | |) | _|| |__\__ \\"
echo " |____/_/ \_\_|\_|\___|\___|/_/ \_\___|___| |_|  |_|\___/|___/|___|____|___/"
echo ""
echo "──────────────────────────────────────────────────────────────────────"
echo ""
echo "  Image:        llms-gpu:$(cat /etc/image-version 2>/dev/null || echo 'unknown')"
echo "  GPU:          $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | paste -sd ', ' || echo 'not available')"
echo "  CPU:          $(lscpu | grep 'Model name' | cut -d':' -f2 | xargs)"
echo "  Memory:       $(free -h | awk '/^Mem:/ {print $2}') total"
echo "  Python:       $(python --version 2>&1 | cut -d' ' -f2)"
echo "  PyTorch:      $(pip list 2>/dev/null | grep -E '^torch\s' | awk '{print $2}' || echo 'not found')"
echo "  Transformers: $(pip list 2>/dev/null | grep -E '^transformers\s' | awk '{print $2}' || echo 'not found')"
echo "  LangChain:    $(pip list 2>/dev/null | grep -E '^langchain\s' | awk '{print $2}' || echo 'not found')"
echo "  CUDA:         $(nvcc --version 2>/dev/null | grep 'release' | sed 's/.*release \([0-9.]*\).*/\1/' || echo 'not available')"
echo "  Driver:       $(cat /proc/driver/nvidia/version 2>/dev/null | head -1 | awk '{print $8}' || echo 'not available')"
echo ""
